-- 文件服务数据库表结构

-- 文件信息表
CREATE TABLE IF NOT EXISTS `file_info` (
    `id` BIGINT NOT NULL COMMENT '文件ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `file_name` VARCHAR(500) NOT NULL COMMENT '文件名（原始文件名）',
    `storage_name` VARCHAR(100) NOT NULL COMMENT '存储文件名（UUID生成）',
    `file_path` VARCHAR(1000) NOT NULL COMMENT '文件路径（相对路径）',
    `file_url` VARCHAR(2000) COMMENT '完整URL',
    `file_size` BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小（字节）',
    `mime_type` VARCHAR(200) COMMENT '文件类型（MIME类型）',
    `extension` VARCHAR(50) COMMENT '文件扩展名',
    `md5_hash` VARCHAR(32) COMMENT '文件MD5哈希值（用于秒传）',
    `sha256_hash` VARCHAR(64) COMMENT '文件SHA256哈希值',
    `bucket_name` VARCHAR(100) NOT NULL COMMENT '存储桶名称',
    `storage_type` VARCHAR(20) NOT NULL DEFAULT 'minio' COMMENT '存储类型：local/minio/oss/cos/s3',
    `category` VARCHAR(20) NOT NULL DEFAULT 'other' COMMENT '文件分类：image/video/audio/document/archive/other',
    `business_type` VARCHAR(50) COMMENT '业务类型：avatar/attachment/document/cover等',
    `business_id` BIGINT COMMENT '关联业务ID',
    `is_public` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否公开访问',
    `access_count` BIGINT NOT NULL DEFAULT 0 COMMENT '访问次数',
    `download_count` BIGINT NOT NULL DEFAULT 0 COMMENT '下载次数',
    `thumbnail_path` VARCHAR(1000) COMMENT '缩略图路径',
    `preview_path` VARCHAR(1000) COMMENT '预览路径',
    `width` INT COMMENT '图片宽度（仅图片/视频）',
    `height` INT COMMENT '图片高度（仅图片/视频）',
    `duration` INT COMMENT '视频/音频时长（秒）',
    `metadata` JSON COMMENT '文件元数据（JSON格式）',
    `upload_user_id` BIGINT COMMENT '上传用户ID',
    `upload_user_name` VARCHAR(100) COMMENT '上传用户名',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-上传中 1-正常 2-已删除',
    `deleted_at` DATETIME COMMENT '删除时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_md5_hash` (`md5_hash`),
    INDEX `idx_sha256_hash` (`sha256_hash`),
    INDEX `idx_business` (`business_type`, `business_id`),
    INDEX `idx_category` (`category`),
    INDEX `idx_status` (`status`),
    INDEX `idx_upload_user` (`upload_user_id`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件信息表';

-- 分片上传任务表
CREATE TABLE IF NOT EXISTS `chunk_upload_task` (
    `id` BIGINT NOT NULL COMMENT '任务ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `upload_id` VARCHAR(64) NOT NULL COMMENT '上传标识（唯一标识一次上传）',
    `file_name` VARCHAR(500) NOT NULL COMMENT '文件名',
    `file_size` BIGINT NOT NULL COMMENT '文件大小（字节）',
    `md5_hash` VARCHAR(32) COMMENT '文件MD5',
    `mime_type` VARCHAR(200) COMMENT '文件类型',
    `bucket_name` VARCHAR(100) NOT NULL COMMENT '存储桶',
    `storage_path` VARCHAR(1000) NOT NULL COMMENT '存储路径',
    `chunk_size` BIGINT NOT NULL COMMENT '分片大小（字节）',
    `total_chunks` INT NOT NULL COMMENT '总分片数',
    `uploaded_chunks` INT NOT NULL DEFAULT 0 COMMENT '已上传分片数',
    `uploaded_indexes` JSON COMMENT '已上传分片索引（JSON数组）',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-上传中 1-已完成 2-已取消 3-已过期',
    `upload_user_id` BIGINT COMMENT '上传用户ID',
    `expire_time` DATETIME COMMENT '过期时间',
    `complete_time` DATETIME COMMENT '完成时间',
    `file_id` BIGINT COMMENT '合并后的文件ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_upload_id` (`upload_id`),
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_md5_hash` (`md5_hash`),
    INDEX `idx_status` (`status`),
    INDEX `idx_expire_time` (`expire_time`),
    INDEX `idx_upload_user` (`upload_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='分片上传任务表';

-- 文件转换任务表
CREATE TABLE IF NOT EXISTS `file_convert_task` (
    `id` BIGINT NOT NULL COMMENT '任务ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `source_file_id` BIGINT NOT NULL COMMENT '源文件ID',
    `source_file_path` VARCHAR(1000) NOT NULL COMMENT '源文件路径',
    `source_format` VARCHAR(50) COMMENT '源文件格式',
    `target_format` VARCHAR(50) NOT NULL COMMENT '目标格式',
    `convert_type` VARCHAR(20) NOT NULL COMMENT '转换类型：preview/thumbnail/format/compress',
    `convert_params` JSON COMMENT '转换参数（JSON格式）',
    `target_file_id` BIGINT COMMENT '目标文件ID',
    `target_file_path` VARCHAR(1000) COMMENT '目标文件路径',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-待处理 1-处理中 2-已完成 3-失败',
    `progress` INT NOT NULL DEFAULT 0 COMMENT '进度（0-100）',
    `error_message` TEXT COMMENT '错误信息',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    `max_retry` INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    `priority` INT NOT NULL DEFAULT 0 COMMENT '优先级（数字越大优先级越高）',
    `start_time` DATETIME COMMENT '开始时间',
    `complete_time` DATETIME COMMENT '完成时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_source_file` (`source_file_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_convert_type` (`convert_type`),
    INDEX `idx_priority` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件转换任务表';

-- 文件访问日志表
CREATE TABLE IF NOT EXISTS `file_access_log` (
    `id` BIGINT NOT NULL COMMENT '日志ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `file_id` BIGINT NOT NULL COMMENT '文件ID',
    `access_type` VARCHAR(20) NOT NULL COMMENT '访问类型：view/download/preview/share',
    `user_id` BIGINT COMMENT '访问用户ID',
    `user_name` VARCHAR(100) COMMENT '访问用户名',
    `access_ip` VARCHAR(50) COMMENT '访问IP',
    `user_agent` VARCHAR(500) COMMENT '用户代理',
    `referer` VARCHAR(1000) COMMENT '来源页面',
    `access_time` DATETIME NOT NULL COMMENT '访问时间',
    `response_time` BIGINT COMMENT '响应时间（毫秒）',
    `success` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否成功',
    `error_message` VARCHAR(500) COMMENT '错误信息',
    PRIMARY KEY (`id`),
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_file_id` (`file_id`),
    INDEX `idx_access_type` (`access_type`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_access_time` (`access_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件访问日志表';

-- 存储配额表
CREATE TABLE IF NOT EXISTS `storage_quota` (
    `id` BIGINT NOT NULL COMMENT 'ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `quota_type` VARCHAR(20) NOT NULL DEFAULT 'total' COMMENT '配额类型：total/image/video/document',
    `max_size` BIGINT NOT NULL COMMENT '最大存储空间（字节）',
    `used_size` BIGINT NOT NULL DEFAULT 0 COMMENT '已使用空间（字节）',
    `max_files` BIGINT COMMENT '最大文件数',
    `used_files` BIGINT NOT NULL DEFAULT 0 COMMENT '已使用文件数',
    `max_single_file_size` BIGINT COMMENT '单文件最大大小（字节）',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_tenant_type` (`tenant_id`, `quota_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储配额表';

-- 文件分享表
CREATE TABLE IF NOT EXISTS `file_share` (
    `id` BIGINT NOT NULL COMMENT '分享ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `file_id` BIGINT NOT NULL COMMENT '文件ID',
    `share_code` VARCHAR(32) NOT NULL COMMENT '分享码',
    `share_password` VARCHAR(32) COMMENT '分享密码',
    `share_type` VARCHAR(20) NOT NULL DEFAULT 'link' COMMENT '分享类型：link/user/department',
    `target_id` BIGINT COMMENT '目标ID（用户ID或部门ID）',
    `permission` VARCHAR(20) NOT NULL DEFAULT 'view' COMMENT '权限：view/download',
    `expire_time` DATETIME COMMENT '过期时间',
    `max_access_count` INT COMMENT '最大访问次数',
    `access_count` INT NOT NULL DEFAULT 0 COMMENT '已访问次数',
    `create_user_id` BIGINT NOT NULL COMMENT '创建用户ID',
    `create_user_name` VARCHAR(100) COMMENT '创建用户名',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_share_code` (`share_code`),
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_file_id` (`file_id`),
    INDEX `idx_create_user` (`create_user_id`),
    INDEX `idx_expire_time` (`expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件分享表';